logo = true
logoImage = "/new/mtf-wiki-long.svg"
logoText = "MtF Wiki"
logoType = "long" # long, short
description = "MtF Wiki is committed to becoming a free, open, and continuously updated transgender knowledge integration site."

themeOptions = ["light", "dark"]

useFaviconGenerator = true # https://www.favicon-generator.org/

enableTocSwitch = true
enableLandingBackground = false
enableSearch = true
enableSearchHighlight = true
enableLangChange = true
enableDarkMode = true
enableBreadcrumb = true
enableBlogBreadcrumb = true
enableEditBtn = false
enableToc = true
enableMenu = true
enableNavbar = true
enableFooter = true
showPoweredBy = true

tocLevels = ["h2", "h3", "h4"]
paginateWindow = 1
taxoPaginate = 13
taxoGroupByDate = "2006" # "2006-01": group by month, "2006": group by year

enableContactUs = true
email = "hi@mtf.wiki"

github = "https://github.com/mtf-wiki/MtF-Wiki"

# comment
enableComment = false
disqus_shortname = ""
commento = false
